pharmacy/urls.py
from django.urls import path
# from .import pharmacistViews,DoctorViews,views,patient_view,clerkViews
from django.contrib.auth import views as auth_views
from .import views, clerkViews, HODViews, DoctorViews, patient_view


urlpatterns=[
    path('',HODViews.adminDashboard,name='admin_dashboard'),
    path('admin_user/patient_form/',HODViews.createPatient,name='patient_form'),
    path('admin_user/all_patients/',HODViews.allPatients,name='all_patients'),
    path('login/',views.loginPage,name='login'),
    path('logout/',views.logoutUser,name='logout'),
    path('admin_user/powbireport1/',views.powerbi1, name='pb1'),
    path('admin_user/powbireport2/',views.powerbi2, name='pb2'),
    # path('get_user_details/', views.get_user_details, name="get_user_details"),

#HOD
path('admin_user/add_pharmacist/',HODViews.createPharmacist,name='add_pharmacist'),
    path('admin_user/manage_pharmacist/',HODViews.managePharmacist,name='manage_pharmacist'),
    path('admin_user/add_doctor/',HODViews.createDoctor,name='add_doctor'),
    path('admin_user/manage_doctor/',HODViews.manageDoctor,name='manage_doctor'),
    path('admin_user/add_pharmacyClerk/',HODViews.createPharmacyClerk,name='add_pharmacyClerk'),
    path('admin_user/admin_user/manage_pharmacyClerk/',HODViews.managePharmacyClerk,name='manage_pharmacyClerk'),
    path('admin_user/add_stock/',HODViews.addStock,name='add_stock'),
    path('admin_user/add_category/',HODViews.addCategory,name='add_category'),
    path('admin_user/manage_stock/',HODViews.manageStock,name='manage_stock'),
    path('admin_user/prescribe_drug/',HODViews.addPrescription,name='prescribe'),
    path('admin_user/edit_patient/<patient_id>/',HODViews.editPatient,name='edit_patient'),
    # path('add_patient_save/',HODViews.editPatientSave,name='edit_patient_save'),

    path('admin_user/delete_patient/<str:pk>/',HODViews.confirmDelete,name='delete_patient'),
    path('admin_user/patient_personalRecords/<pk>/',HODViews.patient_personalRecords,name='patient_record'),
    path('admin_user/delete_prescription/<str:pk>/',HODViews.deletePrescription,name='delete_prescription'),
    path('admin_user/doctor_profile/',DoctorViews.doctorProfile,name='doctor_profile'),
    path('admin_user/hod_profile/',HODViews.hodProfile,name='hod_profile'),
    path('admin_user/delete_doctor/<str:pk>/',HODViews.deleteDoctor,name='delete_doctor'),
    path('admin_user/delete_pharmacist/<str:pk>/',HODViews.deletePharmacist,name='delete_pharmacist'),
    path('admin_user/delete_receptionist/<str:pk>/',HODViews.deletePharmacyClerk,name='delete_clerk'),
    path('admin_user/hod_profile/editAdmin_profile/',HODViews.editAdmin,name='edit-admin'),
    path('admin_user/delete_drug/<str:pk>/',HODViews.deleteDrug,name='delete_drug'),


    path('admin_user/edit_pharmacist/<staff_id>/', HODViews.editPharmacist, name="edit_pharmacist"),
    path('admin_user/edit_doctor/<doctor_id>/', HODViews.editDoctor, name="edit_doctor"),
    path('admin_user/edit_receptionist/<clerk_id>/', HODViews.editPharmacyClerk, name="edit_clerk"),
    path('admin_user/edit_drug/<pk>/', HODViews.editStock, name="edit_drug"),
    path('admin_user/receive_drug/<pk>/', HODViews.receiveDrug, name="receive_drug"),
    path('admin_user/reorder_level/<str:pk>/', HODViews.reorder_level, name="reorder_level"),
    path('admin_user/drug_details/<str:pk>/', HODViews.drugDetails, name="drug_detail"),

#Receptionist
    path('receptionist_profile/',clerkViews.receptionistProfile,name='clerk_profile'),
    path('receptionist_home/',clerkViews.clerkHome,name='clerk_home'),
    path('receptionist/patient_form/',clerkViews.createPatient,name='patient_form2'),
    path('receptionist/all_patients/',clerkViews.allPatients,name='all_patients2'),
    path('receptionist/edit_patient/<patient_id>/',clerkViews.editPatient,name='edit_patient_clerk'),
    path('receptionist/patient_personalRecords/<str:pk>/',clerkViews.patient_personalRecords,name='patient_record_clerk'),
    path('receptionist/delete_patient/<str:pk>/',clerkViews.confirmDelete,name='delete_patient_clerk'),
    # path('receptionist/dispense_drug/<str:pk>/',pharmacistViews.dispenseDrug,name='dispense_drug'),

#Doctor
    path('doctor_home/',DoctorViews.doctorHome,name='doctor_home'),
    path('manage_patients/',DoctorViews.managePatients,name='manage_patient_doctor'),
    path('doctor_prescribe_drug/<str:pk>/',DoctorViews.addPrescription,name='doctor_prescribe2'),
    path('patient_personalDetails/<str:pk>/',DoctorViews.patient_personalDetails,name='patient_record_doctor'),
    path('manage_prescription_doctor/',DoctorViews.managePrescription,name='manage_precrip_doctor'),
    path('doctor_prescribe_delete/<str:pk>/',DoctorViews.deletePrescription,name='doctor_prescrip_delete'),
    path('doctor_prescribe_edit/<str:pk>/',DoctorViews.editPrescription,name='doctor_prescrip_edit'),

#Patients
    path('patient_profile/',patient_view.patientProfile,name='patient_profile'),
    path('patient_home/',patient_view.patientHome,name='patient_home'),
    path('patient_feedback/',patient_view.patient_feedback,name='patient_feedback'),
    path('staff_feedback_save/', patient_view.patient_feedback_save, name="patient_feedback_save"),
    path('taken_home/',patient_view.patient_dispense3,name='taken_home'),
    path('delete_patient_feedback2/<str:pk>/',patient_view.Patientdeletefeedback, name="delete_fed2"),
    path('delete_dispen/',patient_view.myPrescriptionDelete,name='taken_delete'),

]

smartPharm/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pharmacy.urls')),
    path('',include('django.contrib.auth.urls')),
]

pharmacy/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber

from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.core.cache import cache
from django.db.models import BooleanField, ExpressionWrapper, Q
from django.db.models.functions import Now
# Create your models here.

class CustomUser(AbstractUser):
    user_type_data = ((1, "AdminHOD"), (2, "Pharmacist"), (3, "Doctor"), (4, "PharmacyClerk"), (5, "Patients"))
    user_type = models.CharField(default=1, choices=user_type_data, max_length=10)


class Patients(models.Model):
    gender_category = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    admin = models.OneToOneField(CustomUser, null=True, on_delete=models.CASCADE)
    reg_no = models.CharField(max_length=30, null=True, blank=True, unique=True)
    gender = models.CharField(max_length=7, null=True, blank=True, choices=gender_category)
    first_name = models.CharField(max_length=20, null=True, blank=True)
    last_name = models.CharField(max_length=20, null=True, blank=True)
    dob = models.DateTimeField(auto_now_add=False, auto_now=False, null=True, blank=True)
    phone_number = models.CharField(max_length=10, null=True, blank=True)
    profile_pic = models.ImageField(default="patient.jpg", null=True, blank=True)
    age = models.IntegerField(default='0', blank=True, null=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    date_admitted = models.DateTimeField(auto_now_add=True, auto_now=False)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return str(self.admin)


class AdminHOD(models.Model):
    gender_category = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    admin = models.OneToOneField(CustomUser, null=True, on_delete=models.CASCADE)
    emp_no = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=True, choices=gender_category)
    mobile = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    profile_pic = models.ImageField(default="admin.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    date_employed = models.DateTimeField(auto_now_add=True, auto_now=False)
    objects = models.Manager()

    def __str__(self):
        return str(self.admin)


class Pharmacist(models.Model):
    gender_category = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    admin = models.OneToOneField(CustomUser, null=True, on_delete=models.CASCADE)
    emp_no = models.CharField(max_length=100, null=True, blank=True)
    age = models.IntegerField(default='0', blank=True, null=True)
    gender = models.CharField(max_length=100, null=True, choices=gender_category)
    mobile = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    profile_pic = models.ImageField(default="images2.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return str(self.admin)


class Doctor(models.Model):
    gender_category = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    admin = models.OneToOneField(CustomUser, null=True, on_delete=models.CASCADE)
    emp_no = models.CharField(max_length=100, null=True, blank=True)
    age = models.IntegerField(default='0', blank=True, null=True)
    gender = models.CharField(max_length=100, null=True, choices=gender_category)
    mobile = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    profile_pic = models.ImageField(default="doctor.png", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return str(self.admin)


class PharmacyClerk(models.Model):
    gender_category = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    admin = models.OneToOneField(CustomUser, null=True, on_delete=models.CASCADE)
    emp_no = models.CharField(max_length=100, null=True, blank=True)
    gender = models.CharField(max_length=100, null=True, choices=gender_category)
    mobile = models.CharField(max_length=10, null=True, blank=True)
    address = models.CharField(max_length=300, null=True, blank=True)
    profile_pic = models.ImageField(default="images2.png", null=True, blank=True)
    age = models.IntegerField(default='0', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    def __str__(self):
        return str(self.admin)


class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=True)

    def __str__(self):
        return str(self.name)


class Prescription(models.Model):
    patient_id = models.ForeignKey(Patients, null=True, on_delete=models.SET_NULL)
    description = models.TextField(null=True)
    prescribe = models.CharField(max_length=100, null=True)
    date_precribed = models.DateTimeField(auto_now_add=True, auto_now=False)


class ExpiredManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().annotate(
            expired=ExpressionWrapper(Q(valid_to__lt=Now()), output_field=BooleanField())
        )


class Stock(models.Model):
    category = models.ForeignKey(Category, null=True, on_delete=models.CASCADE, blank=True)
    drug_imprint = models.CharField(max_length=6, blank=True, null=True)
    drug_name = models.CharField(max_length=50, blank=True, null=True)
    drug_color = models.CharField(max_length=50, blank=True, null=True)
    drug_shape = models.CharField(max_length=50, blank=True, null=True)
    quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_quantity = models.IntegerField(default='0', blank=True, null=True)
    reorder_level = models.IntegerField(default='0', blank=True, null=True)
    manufacture = models.CharField(max_length=50, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    drug_strength = models.CharField(max_length=10, blank=True, null=True)
    valid_from = models.DateTimeField(blank=True, null=True, default=timezone.now)
    valid_to = models.DateTimeField(blank=False, null=True)
    drug_description = models.TextField(blank=True, max_length=1000, null=True)
    drug_pic = models.ImageField(default="images2.png", null=True, blank=True)
    objects = ExpiredManager()

    def __str__(self):
        return str(self.drug_name)


class Dispense(models.Model):
    patient_id = models.ForeignKey(Patients, on_delete=models.DO_NOTHING, null=True)
    drug_id = models.ForeignKey(Stock, on_delete=models.SET_NULL, null=True, blank=False)
    dispense_quantity = models.PositiveIntegerField(default='1', blank=False, null=True)
    taken = models.CharField(max_length=300, null=True, blank=True)
    stock_ref_no = models.CharField(max_length=300, null=True, blank=True)
    instructions = models.TextField(max_length=300, null=True, blank=False)
    dispense_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)


class PatientFeedback(models.Model):
    id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey(Patients, on_delete=models.CASCADE)
    admin_id = models.ForeignKey(AdminHOD, null=True, on_delete=models.CASCADE)
    pharmacist_id = models.ForeignKey(Pharmacist, null=True, on_delete=models.CASCADE)
    feedback = models.TextField(null=True)
    feedback_reply = models.TextField(null=True)
    admin_created_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()


@receiver(post_save, sender=CustomUser)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        if instance.user_type == 1:
            AdminHOD.objects.create(admin=instance)
        if instance.user_type == 2:
            Pharmacist.objects.create(admin=instance, address="")
        if instance.user_type == 3:
            Doctor.objects.create(admin=instance, address="")
        if instance.user_type == 4:
            PharmacyClerk.objects.create(admin=instance, address="")
        if instance.user_type == 5:
            Patients.objects.create(admin=instance, address="")


@receiver(post_save, sender=CustomUser)
def save_user_profile(sender, instance, **kwargs):
    if instance.user_type == 1:
        instance.adminhod.save()
    if instance.user_type == 2:
        instance.pharmacist.save()
    if instance.user_type == 3:
        instance.doctor.save()
    if instance.user_type == 4:
        instance.pharmacyclerk.save()
    if instance.user_type == 5:
        instance.patients.save()

pharmacy/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect

from django.contrib import messages
from .decorators import *

# Create your views here.

@unautheticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user != None:
            login(request, user)
            user_type = user.user_type
            if user_type == '1':
                return redirect('/')

            elif user_type == '2':
                return redirect('pharmacist_home')

            elif user_type == '3':
                return redirect('doctor_home')
            elif user_type == '4':
                return redirect('clerk_home')
            elif user_type == '5':
                return redirect('patient_home')


            else:
                messages.error(request, "Invalid Login!")
                return redirect('login')
        else:
            messages.error(request, "Invalid Login Credentials!")
            return redirect('login')

    return render(request, 'login.html')


def logoutUser(request):
    logout(request)
    return redirect('login')

def powerbi1(request):


    # context = {
    #     "patients_total": patients
    # }
    return render(request, 'powbi1.html',)

def powerbi2(request):


    # context = {
    #     "patients_total": patients
    # }
    return render(request, 'powbi2.html',)

pharmacy/templates/doctor_templates/base_template.html
{% extends 'base_file.html' %} {% block htm %}

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <h4 style="margin-left: 10px; margin-top: 5px;">Doctor Login </h4>

            <ul class="navbar-nav ml-auto">
                <li class="mx-3">

                    <a href="#" class="sm-submenu-with-image a">
                        <span>{{user.first_name}}  {{user.last_name}}</span>
                        <img src="{{request.user.doctor.profile_pic.url}}" class="img-circle elevation-1" width="38" height="38" alt="">
                        <span class="avatar-status avatar-sm-status avatar-status-success"></span>
                    </a>
                </li>

                <li class="nav-item dropdown ml-3 low">
                    <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent " data-toggle="dropdown" aria-expanded="false" data-wow-delay="0.7s"><img src="https://img.icons8.com/ios/50/000000/settings.png" width="19" height="19">
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">

                        <a href="{% url 'doctor_profile' %}" class="dropdown-item">
                            <i class="fas fa-user-edit mr-2"></i> Update Profile
                        </a>
                        <div class="dropdown-divider"></div>

                        <a href="{%  url 'logout' %}" class="dropdown-item">
                            <i class="fas fa-power-off mr-2"></i> Logout
                        </a>
                        <div class="dropdown-divider"></div>


                    </div>

                </li>


            </ul>

        </nav>

        {% include 'doctor_templates/sidebar.html'%}

        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row ">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark">
                                {% block page_title %} {% endblock page_title %}
                            </h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'doctor_home' %}">Home</a></li>
                                {% block link %} {% endblock link %}
                            </ol>
                        </div>

                    </div>
                </div>
            </div>
            {% block main_content %} {% endblock main_content %}

        </div>
        {% include 'hod_templates/footer.html'%}



    </div>

    <script>
        setTimeout(function() {
            $('.alert').fadeOut();
        }, 1500);
    </script>


    {% endblock htm %}

pharmacy/templates/doctor_templates/doctor_home.html
{% extends 'doctor_templates/base_template.html'%} {% block page_title %}
<h4>Dashboard</h4>
{% endblock page_title %} {% block link %} {% endblock link %} {% block main_content %}
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-sm-12">
                <div class="card-body p-0 d-flex flex-fill illustration oyah">
                    <div class="row g-0 w-100">
                        <div class="col-md-6  col-sm-6">
                            <div class="illustration-text p-3 m-1">
                                <h4 class="illustration-text">Welcome Back, {{user.first_name}}!</h4>
                                <p class="mb-0">Pharmacy Dashboard</p>
                            </div>
                        </div>
                        <div class="col-lg-5 col-md-6  col-sm-6  col-xs-2 align-self-end text-end ">
{#                            <img src="https://appstack.bootlab.io/img/illustrations/customer-support.png" alt="Customer Support" class="img-fluid illustration-img" height="30">#}
                            <img src="https://patientengagementhit.com/images/site/article_headers/_normal/2018-solo-practitioner.jpg" alt="Customer Support" class="img-fluid illustration-img" height="30">
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6 dash-icon">
                <div class=" col-md-6   col-sm-6">
                    <div class="small-box mojahi2">
                        <div class="inner">
                            <h3>{{Prescription_total}}</h3>

                            <p>Total Prescriptions</p>
                        </div>
                        <div class="icon uzer">
                            <i class="fas fa-pills"></i>
                        </div>
                        <a href="{% url 'manage_precrip_doctor' %}" class="small-box-footer">More Info <i class="fas fa-arrow-circle-right"></i></a>
                    </div>
                </div>


            </div>
        </div>
    </div>

</section>

{% endblock main_content %}

pharmacy/templates/doctor_templates/doctor_profile.html
{% extends 'doctor_templates/base_template.html'%} {% block main_content %}
<div class="content">
    <div class="row">
        <div class="col-md-4">
            <div class="card card-body">
                <a href="" class="btn btn-warning"> &#8592; Back to Profile  </a>
                <hr>
                <h3 style="text-align:center;">Account Settings</h3>
                <hr>
                <div class="profile-sidebar">
                    <div class="profile-userpic">


                        <a href="#" class="sm-submenu-with-image">
                            <img src="{{request.user.doctor.profile_pic.url}}" class="img-circle elevation-1" width="200" height="200" alt="">
                            <div class="vl"></div>

                        </a>
                    </div>

                    <div class="profile-usertitle">
                        <div class="profile-usertitle-name">
                            {{request.user.first_name}} {{request.user.last_name}}
                        </div>
                        <div class="profile-usertitle-job">
                            Doctor
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Update Profile</h3>
                </div>
                <form action="" method="post" action="{% url 'doctor_profile' %}" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">

                        {% if messages %}
                        <div class="form-group">
                            <div class="col-12">
                                {% for message in messages %} {% if message.tags == "error" %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% elif message.tags == "success" %}
                                <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                {% endif %} {% endfor %}
                            </div>
                        </div>
                        {% endif %}
                        <h6 class="heading-small text-muted ">User information</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">Username</label>
                                        <input type="text" class="form-control" name="username" value="{{ user.username }}" disabled="disabled">
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">Email </label>
                                        <input type="text" class="form-control" name="email" value="{{ user.email }}" disabled="disabled">
                                    </div>

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label class="form-control-label">First Name </label>
                                        <input type="text" class="form-control" name="first_name" value="{{ user.first_name }}">
                                    </div>
                                </div>
                                <div class="col-lg-6">

                                    <div class="form-group">
                                        <label class="form-control-label">Last Name </label>
                                        <input type="text" class="form-control" name="last_name" value="{{ user.last_name }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <hr class="my-4">
                        <h6 class="heading-small text-muted mb-1">Contact information</h6>
                        <div class="pl-lg-4">
                            <div class="row">
                                <div class="col-md-7">
                                    <div class="form-group focused">
                                        <label class="form-control-label" for="input-address">Address</label>
                                        <input class="form-control" placeholder="Home Address" name="address" type="text" value="{{staff.address}}">
                                    </div>
                                </div>
                                <div class="col-lg-3">
                                    <div class="form-group focused">
                                        <label class="form-control-label" for="input-city">Mobile</label>
                                        <input type="text" id="input-city" name="mobile" class="form-control" placeholder="City" value="{{staff.mobile}}">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">

                                </div>
                            </div>

                        </div>


                        <div class="card-footer mt-3">
                            <button type="submit" class="btn btn-primary">Update Profile</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
</div>


{% endblock %}

pharmacy/templates/doctor_templates/edit_prescription.html
{% extends 'doctor_templates/base_template.html'%} {% load crispy_forms_tags %} {% block page_title %}
<h5>Prescribe</h5>

{% endblock page_title %} {% block link %}
<li class="breadcrumb-item active"><a href="{% url 'manage_patient_doctor' %}"> all patients</a></li>

<li class="breadcrumb-item active">Prescribe</li>

{% endblock link%} {% block main_content %}
<section class="content">


    <div class="row">
        <div class="col-md-12">

            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Add Doctor</h3>
                </div>

                <form method="POST" style="font-size:13px;" class='px-3 py-2'>
                    {% csrf_token %} {% if messages %}
                    <div class="form-group">
                        <div class="col-12">
                            {% for message in messages %} {% if message.tags == "error" %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                            </div>
                            {% elif message.tags == "success" %}
                            <div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                            </div>
                            {% endif %} {% endfor %}
                        </div>
                    </div>
                    {% endif %}
                    <div class="card-body">

                        {{form|crispy}}

                    </div>
                    <input type="submit" class="btn btn-primary">
                </form>
            </div>

        </div>
    </div>
</section>
{% endblock main_content %}